### ISSUE TITLE
Crashes for specific HDF5 file

### ISSUE THREAD

**Issue by renber** [alexschw/ArrayViewer#2]
Hi,

I have a (small) HDF5 file where ArrayViewer crashes with a TypeError during opening:
```
Traceback (most recent call last):
  File "/ArrayViewer/Data.py", line 102, in _add_data
    data = self._validate(h5py.File(str(fname), 'r'))
  File "/ArrayViewer/Data.py", line 68, in _validate
    for key in data if key != "#refs#"}
  File "/ArrayViewer/Data.py", line 68, in <dictcomp>
    for key in data if key != "#refs#"}
  File "/ArrayViewer/Data.py", line 68, in _validate
    for key in data if key != "#refs#"}
  File "/ArrayViewer/Data.py", line 68, in <dictcomp>
    for key in data if key != "#refs#"}
  File "/ArrayViewer/Data.py", line 68, in _validate
    for key in data if key != "#refs#"}
  File "/ArrayViewer/Data.py", line 68, in <dictcomp>
    for key in data if key != "#refs#"}
  File "/ArrayViewer/Data.py", line 72, in _validate
    names = [h5py.h5r.get_name(sd, data.file.id) for sd in d]
  File "/ArrayViewer/Data.py", line 72, in <listcomp>
    names = [h5py.h5r.get_name(sd, data.file.id) for sd in d]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
TypeError: Argument 'ref' has incorrect type (expected h5py.h5r.Reference, got numpy.uint8)
```

File structure is as follows:
![hdf5_structure](https://user-images.githubusercontent.com/3481307/86772118-b9307280-c053-11ea-90f6-213dc6e53d24.png)

timestamps is a linear array with two values
values is a linear array containing variable-sized arrays (here just [1,2,3,4,5])
HDFView can open the file.

I have attached the file:
[sample.zip](https://github.com/alexschw/ArrayViewer/files/4884389/sample.zip)

Can you have a look at it? It would be much appreciated.

**Comment by alexschw** [comment]
Thanks for catching that. It's Fixed now.
