### ISSUE TITLE
Problems with finding Qt when installed by homebrew

### ISSUE THREAD

**Issue by NeuroForLunch** [alexschw/ArrayViewer#3]
```
❯ aview
qt.qpa.plugin: Could not load the Qt platform plugin "cocoa" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: cocoa, minimal, offscreen, webgl.

[1]    40474 abort      aview
```

```
❯ aview
Traceback (most recent call last):
  File "/usr/local/bin/aview", line 5, in <module>
    from ArrayViewer.Viewer import main
  File "/usr/local/lib/python3.9/site-packages/ArrayViewer/Viewer.py", line 15, in <module>
    from PyQt5.QtGui import QColor, QCursor, QIcon
ModuleNotFoundError: No module named 'PyQt5.QtGui'
```

```
❯ aview
Traceback (most recent call last):
  File "/usr/local/bin/aview", line 5, in <module>
    from ArrayViewer.Viewer import main
  File "/usr/local/lib/python3.9/site-packages/ArrayViewer/Viewer.py", line 15, in <module>
    from PyQt5.QtGui import QColor, QCursor, QIcon
ImportError: dlopen(/usr/local/lib/python3.9/site-packages/PyQt5/QtGui.abi3.so, 2): Library not loaded: /usr/local/opt/qt@5/lib/QtCore.framework/Versions/5/QtCore
  Referenced from: /usr/local/lib/python3.9/site-packages/PyQt5/QtGui.abi3.so
  Reason: image not found
```

```
❯ aview
objc[38779]: Class QMacAutoReleasePoolTracker is implemented in both /usr/local/opt/qt@5/lib/QtCore.framework/Versions/5/QtCore (0x1043729f8) and /usr/local/lib/python3.9/site-packages/PyQt5/Qt5/lib/QtCore.framework/Versions/5/QtCore (0x11c1c1198). One of the two will be used. Which one is undefined.
objc[38779]: Class QT_ROOT_LEVEL_POOL__THESE_OBJECTS_WILL_BE_RELEASED_WHEN_QAPP_GOES_OUT_OF_SCOPE is implemented in both /usr/local/opt/qt@5/lib/QtCore.framework/Versions/5/QtCore (0x104372a70) and /usr/local/lib/python3.9/site-packages/PyQt5/Qt5/lib/QtCore.framework/Versions/5/QtCore (0x11c1c1210). One of the two will be used. Which one is undefined.
objc[38779]: Class KeyValueObserver is implemented in both /usr/local/opt/qt@5/lib/QtCore.framework/Versions/5/QtCore (0x104372a98) and /usr/local/lib/python3.9/site-packages/PyQt5/Qt5/lib/QtCore.framework/Versions/5/QtCore (0x11c1c1238). One of the two will be used. Which one is undefined.
objc[38779]: Class RunLoopModeTracker is implemented in both /usr/local/opt/qt@5/lib/QtCore.framework/Versions/5/QtCore (0x104372ae8) and /usr/local/lib/python3.9/site-packages/PyQt5/Qt5/lib/QtCore.framework/Versions/5/QtCore (0x11c1c1288). One of the two will be used. Which one is undefined.
QObject::moveToThread: Current thread (0x7fb4a3731980) is not the object's thread (0x7fb4a57cc040).
Cannot move to target thread (0x7fb4a3731980)

You might be loading two sets of Qt binaries into the same process. Check that all plugins are compiled against the right Qt binaries. Export DYLD_PRINT_LIBRARIES=1 and check that only one set of binaries are being loaded.
qt.qpa.plugin: Could not load the Qt platform plugin "cocoa" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: cocoa, minimal, offscreen, webgl.

[1]    38779 abort      aview
```

aview also checks in the wrong place for its own logo image. Perhaps you just need to push the updated code to pip?

**Comment by NeuroForLunch** [comment]
Compiled from source... same issues. Also, somehow the source version ends with 6 instead of 7?

**Comment by alexschw** [comment]
Hey there, thank you for asking.
It seems as though you are using OSX. I have sadly no Mac system to test it on. I will try to reproduce it using homebrew on Linux. 

Can you please provide a little more information on how you installed it. Also what version of Qt is installed on your system. Thank you.

**Comment by NeuroForLunch** [comment]
I installed it with `brew install qt@5` which installs 5.15.2... here's the output from the install: `Linking /usr/local/Cellar/pyqt@5/5.15.4_2... 1321 symlinks created.`

And somehow there are 2 QtCore files in different locations and they are different sizes but all the other python and non python programs that need Qt work fine.

**Comment by alexschw** [comment]
Okay. I think I know what happend here. As a requirement I am installing PyQt5. But as it is already installed with the name "PyQt@5" it is not found during installation. I will have to think about a better solution for checking. To solve your problem you might delete/uninstall the PyQt5 installed by my script. (Maybe check where import PyQt5 leads afterwards) 
Thank you.
